export const BASE_URL = 'https://therealotakus-api.vercel.app/';
// export const BASE_URL = '';

// POPULAR ANIME CONSTANT
export const POPULAR_ANIME_LIST = 'POPULAR_ANIME_LIST';
export const POPULAR_ANIME_LIST_LOADING = 'POPULAR_ANIME_LIST_LOADING';
export const POPULAR_ANIME_LIST_ERROR = 'POPULAR_ANIME_LIST_ERROR';
export const NEXT_PAGE = 'NEXT_PAGE';
export const RESET_PAGE = 'RESET_PAGE';
export const RESET = 'RESET';

// ANIME DETAIL CONSTANT
export const GET_ANIME_DETAILS = 'GET_ANIME_DETAILS';
export const CLEAR_ANIME_DETAILS = 'CLEAR_ANIME_DETAILS';
export const SET_ANIME_DETAILS_LOADING = 'SET_ANIME_DETAILS_LOADING';
export const SET_ANIME_DETAILS_ERROR = 'SET_ANIME_DETAILS_ERROR';

// SELECTED ANIME CONSTANT
export const SET_SELECTED_ANIME = 'SET_SELECTED_ANIME';
export const CLEAR_SELECTED_ANIME = 'CLEAR_SELECTED_ANIME';

// GENRE ANIME CONSTANT
export const GET_ANIME_GENRE_LIST = 'GET_ANIME_GENRE_LIST';
export const SET_ANIME_GENRE_LOADING = 'SET_ANIME_GENRE_LOADING';
export const SET_ANIME_GENRE_ERROR = 'SET_ANIME_GENRE_ERROR';

export const GET_GENRE_ANIME_LIST = 'GET_GENRE_ANIME_LIST';
export const SET_GENRE_ANIME_LOADING = 'SET_GENRE_ANIME_LOADING';
export const SET_GENRE_ANIME_ERROR = 'SET_GENRE_ANIME_ERROR';
export const GENRE_ANIME_NEXT_PAGE = 'GENRE_ANIME_NEXT_PAGE';
export const GENRE_ANIME_RESET_PAGE = 'GENRE_ANIME_RESET_PAGE';
export const GENRE_ANIME_RESET = 'GENRE_ANIME_RESET';
export const GENRE_ANIME_CLEAR = 'GENRE_ANIME_CLEAR';

// PLAYER CONSTANT
export const GET_PLAYER_URLS = 'GET_PLAYER_URLS';
export const SET_PLAYER_LOADING = 'SET_PLAYER_LOADING';
export const SET_PLAYER_ERROR = 'SET_PLAYER_ERROR';

// SEARCH CONSTANT
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const GET_SEARCH = 'GET_SEARCH';
export const SET_SEARCH_LOADING = 'SET_SEARCH_LOADING';
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';

// FAVOURITES CONSTANT
export const GET_FAVOURITES = 'GET_FAVOURITES';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const REMOVE_FAVOURITES = 'REMOVE_FAVOURITES';

// THEME CONSTANT
export const TOGGLE_THEME = 'TOGGLE_THEME';

// USER CHAT CONSTANT
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME';
export const CHANGE_PROFILE_PIC = 'CHANGE_PROFILE_PIC';

// APP INFO CONSTANT
export const SET_APP_INFO = 'SET_APP_INFO';
export const APP_UPDATED = 'APP_UPDATED';
export const HIDE_BANNER = 'HIDE_BANNER';
